"use client";
import { useState, useEffect } from "react";
import { supabase } from "@/lib/supabaseClient";
import {
    Sparkles,
    BookOpen,
    Clock,
    Award,
    ChevronRight,
    Loader2,
    RefreshCw,
    CheckCircle,
    Target,
    Trophy
} from "lucide-react";
import PointsNotification from "./PointsNotification";

export default function LearningPathGenerator({ userId }) {
    const [interests, setInterests] = useState([]);
    const [interestInput, setInterestInput] = useState("");
    const [learningPaths, setLearningPaths] = useState([]);
    const [completedPaths, setCompletedPaths] = useState([]);
    const [isGenerating, setIsGenerating] = useState(false);
    const [error, setError] = useState(null);
    const [selectedPath, setSelectedPath] = useState(null);
    const [enrolledPaths, setEnrolledPaths] = useState([]);
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
    const [educationLevel, setEducationLevel] = useState("");
    const [showPointsNotification, setShowPointsNotification] = useState(false);
    const [pointsData, setPointsData] = useState(null);
    const [completingModule, setCompletingModule] = useState(null);

    const commonInterests = [
        "Climate Change",
        "Renewable Energy",
        "Water Conservation",
        "Recycling",
        "Wildlife Protection",
        "Sustainable Agriculture",
        "Ocean Conservation",
        "Air Quality",
        "Zero Waste",
        "Green Technology"
    ];

    // Education level-based default interests
    const getDefaultInterests = (eduLevel) => {
        const isCollege = eduLevel?.toLowerCase().includes("college") ||
            eduLevel?.toLowerCase().includes("university");

        if (isCollege) {
            // College students: more advanced topics
            return ["Climate Change", "Renewable Energy", "Green Technology"];
        } else {
            // School students: foundational topics
            const gradeMatch = eduLevel?.match(/\d+/);
            const grade = gradeMatch ? parseInt(gradeMatch[0]) : 5;

            if (grade <= 5) {
                return ["Recycling", "Water Conservation", "Wildlife Protection"];
            } else if (grade <= 8) {
                return ["Climate Change", "Water Conservation", "Recycling"];
            } else {
                return ["Climate Change", "Renewable Energy", "Sustainable Agriculture"];
            }
        }
    };

    useEffect(() => {
        if (userId) {
            initializeComponent();
        }
    }, [userId]);

    const initializeComponent = async () => {
        await fetchEducationLevel();
        await fetchEnrolledPaths();
        await fetchCompletedPaths();
        await fetchExistingInterestsAndGenerate();
    };

    const fetchEducationLevel = async () => {
        const { data } = await supabase
            .from("user_details")
            .select("education_level")
            .eq("user_id", userId)
            .single();

        if (data?.education_level) {
            setEducationLevel(data.education_level);
        }
    };

    const fetchExistingInterestsAndGenerate = async () => {
        const { data } = await supabase
            .from("student_interests")
            .select("interests")
            .eq("student_id", userId)
            .single();

        let selectedInterests = [];

        if (data?.interests && data.interests.length > 0) {
            // User has saved interests
            selectedInterests = data.interests;
            setInterests(selectedInterests);
        } else {
            // Auto-select interests based on education level
            selectedInterests = getDefaultInterests(educationLevel);
            setInterests(selectedInterests);
        }

        // Always try to fetch existing learning paths from database first
        // This runs on every component mount (including page refresh)
        await fetchOrGeneratePaths(selectedInterests);
    };

    const fetchOrGeneratePaths = async (selectedInterests) => {
        setIsGenerating(true);
        setError(null);

        try {
            console.log("🔍 Checking database for existing learning paths...");
            console.log("User ID:", userId);

            // Fetch both AI-generated learning paths AND teacher lesson plans
            const [aiPathsResponse, teacherPlansResponse] = await Promise.all([
                // AI-generated learning paths
                supabase
                    .from("learning_paths")
                    .select("*")
                    .eq("created_by", userId)
                    .eq("is_active", true)
                    .order("created_at", { ascending: false })
                    .limit(3),
                // Teacher lesson plans
                fetch(`/api/student-lesson-plans?studentId=${userId}`)
            ]);

            const { data: existingPaths, error: fetchError } = aiPathsResponse;

            // Handle teacher plans response
            let teacherPlansData = { lessonPlans: [] };
            if (teacherPlansResponse.ok) {
                teacherPlansData = await teacherPlansResponse.json();
                console.log('📚 Teacher plans response:', teacherPlansData);
            } else {
                console.error('❌ Failed to fetch teacher plans:', teacherPlansResponse.status);
                const errorText = await teacherPlansResponse.text();
                console.error('Error details:', errorText);
            }

            if (fetchError) {
                console.error("❌ Error fetching AI paths:", fetchError);
            }

            console.log("📊 Database query result:", {
                aiPathsFound: existingPaths?.length || 0,
                teacherPlansFound: teacherPlansData.lessonPlans?.length || 0,
                teacherPlansDebug: teacherPlansData.debug
            });

            // Combine AI paths and teacher lesson plans
            const combinedPaths = [
                ...(existingPaths || []),
                ...(teacherPlansData.lessonPlans || [])
            ];

            console.log('🔗 Combined paths:', combinedPaths.length, 'total');

            // If we have existing paths (AI or teacher), use them
            if (combinedPaths.length > 0) {
                console.log("✅ Using existing learning paths from database");
                setLearningPaths(combinedPaths);
                setIsGenerating(false);
                return;
            }

            // No existing paths, generate new ones with AI
            console.log("🤖 No existing paths found, generating new ones with AI");
            await generatePathsWithAI(selectedInterests);
        } catch (err) {
            console.error("❌ Error in fetchOrGeneratePaths:", err);
            setIsGenerating(false);
        }
    };

    const generatePathsWithAI = async (selectedInterests) => {
        try {
            console.log("🚀 Calling AI API to generate learning paths...");
            const response = await fetch("/api/learning-paths", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    userId,
                    interests: selectedInterests,
                    regenerate: false
                })
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "Failed to generate learning paths");
            }

            console.log("✅ AI generated paths successfully:", data.learningPaths?.length || 0, "paths");
            // The API already saves paths to database, just set them in state
            setLearningPaths(data.learningPaths);
        } catch (err) {
            console.error("❌ AI generation error:", err);
            // Don't show error on auto-generation, just log it
        } finally {
            setIsGenerating(false);
        }
    };



    const fetchEnrolledPaths = async () => {
        // Fetch both learning path progress and lesson plan progress (only non-completed ones)
        const [learningPathProgress, lessonPlanProgress] = await Promise.all([
            supabase
                .from("student_learning_progress")
                .select(`
                    *,
                    learning_paths (*)
                `)
                .eq("student_id", userId)
                .is("completed_at", null), // Only fetch non-completed paths
            supabase
                .from("lesson_plan_progress")
                .select("*")
                .eq("student_id", userId)
                .is("completed_at", null) // Only fetch non-completed lesson plans
        ]);

        const combinedProgress = [
            ...(learningPathProgress.data || []),
            ...(lessonPlanProgress.data || []).map(lp => ({
                ...lp,
                learning_path_id: lp.lesson_plan_id, // Map to common field
                is_lesson_plan: true
            }))
        ];

        setEnrolledPaths(combinedProgress);
    };

    const fetchCompletedPaths = async () => {
        try {
            // Fetch completed learning paths
            const { data: completedLearningPaths } = await supabase
                .from("student_learning_progress")
                .select(`
                    *,
                    learning_paths (*)
                `)
                .eq("student_id", userId)
                .not("completed_at", "is", null)
                .order("completed_at", { ascending: false });

            // Fetch completed lesson plans
            const { data: completedLessonPlans } = await supabase
                .from("lesson_plan_progress")
                .select(`
                    *,
                    lesson_plans (*)
                `)
                .eq("student_id", userId)
                .not("completed_at", "is", null)
                .order("completed_at", { ascending: false });

            // Combine and format completed paths
            const combinedCompleted = [
                ...(completedLearningPaths || [])
                    .filter(lp => lp.learning_paths) // Filter out null joins
                    .map(lp => ({
                        ...lp.learning_paths,
                        id: lp.learning_path_id,
                        progressPercentage: lp.progress_percentage,
                        pointsEarned: lp.points_earned,
                        completedAt: lp.completed_at,
                        is_lesson_plan: false
                    })),
                ...(completedLessonPlans || [])
                    .filter(lp => lp.lesson_plans) // Filter out null joins
                    .map(lp => ({
                        ...lp.lesson_plans,
                        id: lp.lesson_plan_id,
                        progressPercentage: lp.progress_percentage,
                        pointsEarned: lp.points_earned,
                        completedAt: lp.completed_at,
                        is_lesson_plan: true,
                        is_teacher_plan: true
                    }))
            ].filter(path => path && path.id); // Filter out any null/undefined paths

            setCompletedPaths(combinedCompleted);
        } catch (error) {
            console.error('Error fetching completed paths:', error);
        }
    };

    const addInterest = (interest) => {
        if (!interests.includes(interest) && interests.length < 5) {
            setInterests([...interests, interest]);
        }
    };

    const removeInterest = (interest) => {
        setInterests(interests.filter(i => i !== interest));
    };

    const generatePaths = async () => {
        if (interests.length === 0) {
            setError("Please select at least one interest");
            return;
        }

        setError(null);

        // When user manually clicks generate, always create new paths (regenerate: true)
        setIsGenerating(true);

        try {
            const response = await fetch("/api/learning-paths", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    userId,
                    interests,
                    regenerate: true // Force regeneration on manual click
                })
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "Failed to generate learning paths");
            }

            setLearningPaths(data.learningPaths);
        } catch (err) {
            setError(err.message);
        } finally {
            setIsGenerating(false);
        }
    };

    const enrollInPath = async (pathId) => {
        try {
            // Check if this is a teacher lesson plan
            const path = learningPaths.find(p => p.id === pathId);
            const isTeacherPlan = path?.is_teacher_plan;

            if (isTeacherPlan) {
                // For teacher lesson plans, use lesson_plan_progress table
                const { error } = await supabase
                    .from("lesson_plan_progress")
                    .insert({
                        student_id: userId,
                        lesson_plan_id: pathId,
                        completed_activities: [],
                        progress_percentage: 0,
                        points_earned: 0
                    });

                if (error) {
                    console.error('Error enrolling in lesson plan:', error);
                    throw error;
                }
            } else {
                // For AI-generated learning paths, use student_learning_progress table
                const { error } = await supabase
                    .from("student_learning_progress")
                    .insert({
                        student_id: userId,
                        learning_path_id: pathId,
                        progress_percentage: 0,
                        current_module: 0,
                        completed_modules: []
                    });

                if (error) {
                    console.error('Error enrolling in learning path:', error);
                    throw error;
                }
            }

            await fetchEnrolledPaths();
            alert("Successfully enrolled in learning path!");
        } catch (err) {
            alert("Error enrolling: " + err.message);
        }
    };

    const completeModule = async (pathId, moduleIndex) => {
        setCompletingModule(`${pathId}-${moduleIndex}`);
        try {
            // Check if this is a teacher lesson plan
            const path = learningPaths.find(p => p.id === pathId);
            const isTeacherPlan = path?.is_teacher_plan;

            const endpoint = isTeacherPlan ? '/api/complete-lesson-activity' : '/api/complete-learning-module';
            const requestBody = isTeacherPlan
                ? { studentId: userId, lessonPlanId: pathId, activityIndex: moduleIndex }
                : { studentId: userId, learningPathId: pathId, moduleIndex: moduleIndex };

            const response = await fetch(endpoint, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(requestBody)
            });

            const data = await response.json();
            if (data.success) {
                const achievementText = isTeacherPlan
                    ? (data.isLessonComplete ? "Lesson Plan Completed! 🎓" : null)
                    : (data.isPathComplete ? "Path Completed! 🎓" : null);

                setPointsData({
                    pointsEarned: data.totalPointsEarned,
                    newTotal: data.newTotalPoints,
                    rankChange: null,
                    achievement: achievementText,
                    activityType: isTeacherPlan ? 'lesson_plan' : 'learning_path'
                });
                setShowPointsNotification(true);
                // Refresh both enrolled and completed paths
                await fetchEnrolledPaths();
                await fetchCompletedPaths();
            }
        } catch (error) {
            console.error('Error completing module:', error);
            alert('Failed to complete module. Please try again.');
        } finally {
            setCompletingModule(null);
        }
    };

    const getDifficultyColor = (difficulty) => {
        switch (difficulty) {
            case "beginner": return "bg-emerald-500/15 text-emerald-300 border-emerald-500/30";
            case "intermediate": return "bg-amber-500/15 text-amber-300 border-amber-500/30";
            case "advanced": return "bg-red-500/15 text-red-300 border-red-500/30";
            default: return "bg-gray-500/15 text-gray-300 border-gray-500/30";
        }
    };

    return (
        <div className="space-y-6">
            {/* Interest Selection */}
            <div className="bg-[#0f0f0f] rounded-2xl border border-[#1a1a1a] p-6">
                <div className="flex items-center gap-2 mb-4">
                    <Sparkles className="h-5 w-5 text-emerald-400" />
                    <h3 className="text-xl font-bold text-white">Select Your Interests</h3>
                </div>

                <p className="text-sm text-gray-400 mb-4">
                    {educationLevel && (
                        <span className="text-emerald-400">
                            ✨ Auto-selected topics for {educationLevel} students.
                        </span>
                    )} Choose up to 5 topics you're passionate about (selected: {interests.length}/5)
                </p>

                {/* Selected Interests */}
                {interests.length > 0 && (
                    <div className="flex flex-wrap gap-2 mb-4">
                        {interests.map((interest) => (
                            <span
                                key={interest}
                                className="px-3 py-1.5 rounded-full bg-emerald-500/20 text-emerald-300 text-sm border border-emerald-500/30 flex items-center gap-2"
                            >
                                {interest}
                                <button
                                    onClick={() => removeInterest(interest)}
                                    className="hover:text-emerald-100"
                                >
                                    ×
                                </button>
                            </span>
                        ))}
                    </div>
                )}

                {/* Common Interests */}
                <div className="flex flex-wrap gap-2 mb-4">
                    {commonInterests.map((interest) => (
                        <button
                            key={interest}
                            onClick={() => addInterest(interest)}
                            disabled={interests.includes(interest) || interests.length >= 5}
                            className={`px-3 py-1.5 rounded-full text-sm border transition-all ${interests.includes(interest)
                                ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/30 cursor-not-allowed"
                                : "bg-[#1a1a1a] text-gray-300 border-[#2a2a2a] hover:bg-[#222] hover:border-emerald-500/30"
                                }`}
                        >
                            {interest}
                        </button>
                    ))}
                </div>

                {/* Custom Interest Input */}
                <div className="flex gap-2">
                    <input
                        type="text"
                        placeholder="Add custom interest..."
                        value={interestInput}
                        onChange={(e) => setInterestInput(e.target.value)}
                        onKeyPress={(e) => {
                            if (e.key === "Enter" && interestInput.trim()) {
                                addInterest(interestInput.trim());
                                setInterestInput("");
                            }
                        }}
                        className="flex-1 px-4 py-2 bg-[#0a0d0b] border border-[#2a2a2a] rounded-xl text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-emerald-500/60"
                    />
                    <button
                        onClick={generatePaths}
                        disabled={isGenerating || interests.length === 0}
                        className="px-6 py-2 bg-emerald-500 hover:bg-emerald-400 text-[#04210f] font-semibold rounded-xl transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                    >
                        {isGenerating ? (
                            <>
                                <Loader2 className="h-4 w-4 animate-spin" />
                                Generating...
                            </>
                        ) : (
                            <>
                                <Sparkles className="h-4 w-4" />
                                Generate Paths
                            </>
                        )}
                    </button>
                </div>

                {error && (
                    <div className="mt-4 p-3 bg-red-500/10 border border-red-500/30 rounded-xl">
                        <p className="text-red-300 text-sm">{error}</p>
                    </div>
                )}
            </div>

            {/* Generated Learning Paths */}
            {isGenerating && learningPaths.length === 0 && (
                <div className="bg-[#0f0f0f] rounded-2xl border border-[#1a1a1a] p-12 text-center">
                    <Loader2 className="h-12 w-12 text-emerald-400 animate-spin mx-auto mb-4" />
                    <h3 className="text-xl font-bold text-white mb-2">Generating Your Personalized Learning Paths</h3>
                    <p className="text-gray-400">
                        Our AI is creating custom learning paths based on your education level and interests...
                    </p>
                </div>
            )}

            {learningPaths.length > 0 && (
                <div className="space-y-4">
                    <div className="flex items-center justify-between">
                        <h3 className="text-2xl font-bold text-white">Your Personalized Learning Paths</h3>
                        <button
                            onClick={generatePaths}
                            className="text-emerald-400 hover:text-emerald-300 text-sm font-semibold flex items-center gap-2"
                        >
                            <RefreshCw className="h-4 w-4" />
                            Generate New Paths
                        </button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                        {learningPaths.filter(path => {
                            // Filter out completed paths
                            return !completedPaths.some(cp => cp.id === path.id);
                        }).map((path) => {
                            // Check enrollment for both learning paths and lesson plans
                            const isEnrolled = enrolledPaths.some(ep =>
                                ep.learning_path_id === path.id || ep.lesson_plan_id === path.id
                            );

                            return (
                                <div
                                    key={path.id}
                                    className="bg-[#0f0f0f] rounded-2xl border border-[#1a1a1a] p-5 hover:shadow-lg hover:border-emerald-500/30 transition-all cursor-pointer"
                                    onClick={() => setSelectedPath(path)}
                                >
                                    <div className="flex items-start justify-between mb-3">
                                        <div className="flex gap-2">
                                            <span className={`px-3 py-1 rounded-full text-xs border ${getDifficultyColor(path.difficulty)}`}>
                                                {path.difficulty}
                                            </span>
                                            {path.is_teacher_plan && (
                                                <span className="px-3 py-1 rounded-full text-xs border bg-blue-500/15 text-blue-300 border-blue-500/30">
                                                    👨‍🏫 Teacher
                                                </span>
                                            )}
                                        </div>
                                        {isEnrolled && (
                                            <CheckCircle className="h-5 w-5 text-emerald-400" />
                                        )}
                                    </div>

                                    <h4 className="text-lg font-bold text-white mb-2">{path.title}</h4>
                                    <p className="text-sm text-gray-400 mb-4 line-clamp-2">{path.description}</p>

                                    <div className="space-y-2 mb-4">
                                        <div className="flex items-center gap-2 text-sm text-gray-400">
                                            <BookOpen className="h-4 w-4 text-emerald-400" />
                                            {Array.isArray(path.modules) ? path.modules.length : 0} modules
                                        </div>
                                        <div className="flex items-center gap-2 text-sm text-gray-400">
                                            <Clock className="h-4 w-4 text-emerald-400" />
                                            {path.estimated_duration}
                                        </div>
                                        <div className="flex items-center gap-2 text-sm text-gray-400">
                                            <Award className="h-4 w-4 text-emerald-400" />
                                            {path.total_points} points
                                        </div>
                                    </div>

                                    {!isEnrolled ? (
                                        <button
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                enrollInPath(path.id);
                                            }}
                                            className="w-full bg-emerald-500 hover:bg-emerald-400 text-[#04210f] font-semibold py-2 rounded-xl transition-colors flex items-center justify-center gap-2"
                                        >
                                            Enroll Now
                                            <ChevronRight className="h-4 w-4" />
                                        </button>
                                    ) : (
                                        <button
                                            className="w-full bg-emerald-500/20 text-emerald-300 font-semibold py-2 rounded-xl border border-emerald-500/30 flex items-center justify-center gap-2"
                                        >
                                            <CheckCircle className="h-4 w-4" />
                                            Enrolled
                                        </button>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </div>
            )}

            {/* Path Details Modal */}
            {selectedPath && (
                <div
                    className="fixed inset-0 bg-black/80 flex items-center justify-center p-4 z-50"
                    onClick={() => setSelectedPath(null)}
                >
                    <div
                        className="bg-[#0f0f0f] rounded-2xl border border-[#1a1a1a] p-6 max-w-2xl w-full max-h-[80vh] overflow-y-auto"
                        onClick={(e) => e.stopPropagation()}
                    >
                        <div className="flex items-start justify-between mb-4">
                            <div>
                                <h3 className="text-2xl font-bold text-white mb-2">{selectedPath.title}</h3>
                                <span className={`px-3 py-1 rounded-full text-xs border ${getDifficultyColor(selectedPath.difficulty)}`}>
                                    {selectedPath.difficulty}
                                </span>
                            </div>
                            <button
                                onClick={() => setSelectedPath(null)}
                                className="text-gray-400 hover:text-white text-2xl"
                            >
                                ×
                            </button>
                        </div>

                        <p className="text-gray-300 mb-6">{selectedPath.description}</p>

                        <div className="space-y-4">
                            <h4 className="text-lg font-bold text-white">Modules</h4>
                            {Array.isArray(selectedPath.modules) && selectedPath.modules.map((module, index) => {
                                // Check if this module is completed
                                const enrolledPath = enrolledPaths.find(ep => 
                                    ep.learning_path_id === selectedPath.id || ep.lesson_plan_id === selectedPath.id
                                );
                                
                                // Check if module is completed
                                let isModuleCompleted = false;
                                if (enrolledPath) {
                                    if (enrolledPath.is_lesson_plan) {
                                        // For lesson plans, check completed_activities array
                                        const completedActivities = enrolledPath.completed_activities || [];
                                        isModuleCompleted = completedActivities.includes(index);
                                    } else {
                                        // For learning paths, check completed_modules array
                                        const completedModules = enrolledPath.completed_modules || [];
                                        isModuleCompleted = completedModules.includes(index);
                                    }
                                }

                                return (
                                    <div key={index} className="bg-[#1a1a1a] rounded-xl p-4">
                                        <div className="flex items-start justify-between mb-2">
                                            <h5 className="font-semibold text-white">{index + 1}. {module.title}</h5>
                                            <div className="flex items-center gap-2">
                                                {isModuleCompleted && (
                                                    <CheckCircle className="h-4 w-4 text-emerald-400" />
                                                )}
                                                <span className="text-sm text-emerald-400 font-semibold">{module.points} pts</span>
                                            </div>
                                        </div>
                                        <p className="text-sm text-gray-400 mb-3">{module.description}</p>
                                        <div className="flex items-center gap-2 text-xs text-gray-500">
                                            <Clock className="h-3 w-3" />
                                            {module.duration}
                                        </div>
                                        {module.activities && (
                                            <div className="mt-3">
                                                <p className="text-xs text-gray-500 mb-1">Activities:</p>
                                                <ul className="list-disc list-inside text-sm text-gray-400 space-y-1">
                                                    {module.activities.map((activity, i) => (
                                                        <li key={i}>{activity}</li>
                                                    ))}
                                                </ul>
                                            </div>
                                        )}
                                        {/* Complete Module Button */}
                                        <button
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                completeModule(selectedPath.id, index);
                                            }}
                                            disabled={completingModule === `${selectedPath.id}-${index}` || isModuleCompleted}
                                            className={`w-full mt-3 font-semibold py-2 rounded-lg transition-colors flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed ${
                                                isModuleCompleted 
                                                    ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 cursor-not-allowed" 
                                                    : "bg-emerald-500 hover:bg-emerald-400 text-[#04210f]"
                                            }`}
                                        >
                                            {completingModule === `${selectedPath.id}-${index}` ? (
                                                <>
                                                    <Loader2 className="h-4 w-4 animate-spin" />
                                                    Completing...
                                                </>
                                            ) : isModuleCompleted ? (
                                                <>
                                                    <CheckCircle className="h-4 w-4" />
                                                    Module Completed ({module.points} pts)
                                                </>
                                            ) : (
                                                <>
                                                    <CheckCircle className="h-4 w-4" />
                                                    Complete Module ({module.points} pts)
                                                </>
                                            )}
                                        </button>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                </div>
            )}

            {/* Completed Learning Paths Section */}
            {completedPaths.length > 0 && (
                <div className="mt-8 space-y-4">
                    <div className="flex items-center justify-between">
                        <h3 className="text-2xl font-bold text-white flex items-center gap-2">
                            <CheckCircle className="h-6 w-6 text-emerald-400" />
                            Completed Learning Paths
                        </h3>
                        <span className="text-sm text-gray-400">
                            {completedPaths.length} path{completedPaths.length !== 1 ? 's' : ''} completed
                        </span>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                        {completedPaths.map((path) => (
                            <div
                                key={path.id}
                                className="bg-[#0f0f0f] rounded-2xl border border-emerald-500/30 p-5 opacity-75"
                            >
                                <div className="flex items-start justify-between mb-3">
                                    <div className="flex gap-2">
                                        <span className={`px-3 py-1 rounded-full text-xs border ${getDifficultyColor(path.difficulty)}`}>
                                            {path.difficulty}
                                        </span>
                                        {path.is_teacher_plan && (
                                            <span className="px-3 py-1 rounded-full text-xs border bg-blue-500/15 text-blue-300 border-blue-500/30">
                                                👨‍🏫 Teacher
                                            </span>
                                        )}
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <CheckCircle className="h-5 w-5 text-emerald-400" />
                                        <span className="px-3 py-1 rounded-full text-xs bg-emerald-500/15 text-emerald-300 border border-emerald-500/30">
                                            Completed
                                        </span>
                                    </div>
                                </div>

                                <h4 className="text-lg font-bold text-white mb-2">{path.title}</h4>
                                <p className="text-sm text-gray-400 mb-4 line-clamp-2">{path.description}</p>

                                <div className="space-y-2 mb-4">
                                    <div className="flex items-center gap-2 text-sm text-emerald-400">
                                        <Award className="h-4 w-4" />
                                        {path.pointsEarned || path.total_points} points earned
                                    </div>
                                    <div className="flex items-center gap-2 text-sm text-gray-400">
                                        <Target className="h-4 w-4" />
                                        {path.progressPercentage || 100}% complete
                                    </div>
                                    {path.completedAt && (
                                        <div className="flex items-center gap-2 text-sm text-gray-400">
                                            <Clock className="h-4 w-4" />
                                            Completed {new Date(path.completedAt).toLocaleDateString()}
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Points Notification */}
            {showPointsNotification && pointsData && (
                <PointsNotification
                    show={showPointsNotification}
                    onClose={() => setShowPointsNotification(false)}
                    pointsEarned={pointsData.pointsEarned}
                    newTotal={pointsData.newTotal}
                    rankChange={pointsData.rankChange}
                    achievement={pointsData.achievement}
                    activityType={pointsData.activityType}
                />
            )}
        </div>
    );
}
